name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: action/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag ccarlsson/labbsalen:$(date +$s) --tag ccarlsson/labbsalen:latest 
    - name: Push Docker Image with date
      run: docker push ccarlsson/labbsalen:$(date +$s)
    - name: Push Docker Image latest
      run: docker push ccarlsson/labbsalen:latest
