name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ccarlsson/labbsalen:$(date +%s) --tag ccarlsson/labbsalen:latest
    
    - name: Login to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push Docker image with date
      run: docker push ccarlsson/labbsalen:$(date +%s)
    - name: Push Docker image latest
      run: docker push ccarlsson/labbsalen:latest
